# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agento < Formula
  desc "Agento — AI Agents Platform"
  homepage "https://github.com/shaharia-lab/agento"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.2.0/agento_Darwin_x86_64.tar.gz"
      sha256 "b1e7b61946be91623f33aa549bc0161f2826a0140796ceaa1cd1ef2d371693ba"

      define_method(:install) do
        bin.install "agento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.2.0/agento_Darwin_arm64.tar.gz"
      sha256 "40174101e4df4ded0598231d37356071552b13c618c1363130519aadfc0a3aa5"

      define_method(:install) do
        bin.install "agento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.2.0/agento_Linux_x86_64.tar.gz"
      sha256 "557a3e0d467ff39be5cfc536af053c8b290f46ab04143c8fca0c905269a03ca7"
      define_method(:install) do
        bin.install "agento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.2.0/agento_Linux_arm64.tar.gz"
      sha256 "f7e76ac500611b1ca41f7e8c404a6541438492d3ec5afede8ab01c9c79942374"
      define_method(:install) do
        bin.install "agento"
      end
    end
  end

  test do
    system "#{bin}/agento", "--version"
  end
end
