# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agento < Formula
  desc "Agento — AI Agents Platform"
  homepage "https://github.com/shaharia-lab/agento"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.11.2/agento_Darwin_x86_64.tar.gz"
      sha256 "3fffd6286ee0ecc097e8c1ab2655296636366b7b3bdcfb440b6ddce6f0adc8cf"

      define_method(:install) do
        bin.install "agento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.11.2/agento_Darwin_arm64.tar.gz"
      sha256 "c3f06977c77aec09d364e77d340625f2177bdf3343b72638597f7e6a1313fb99"

      define_method(:install) do
        bin.install "agento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.11.2/agento_Linux_x86_64.tar.gz"
      sha256 "224c5c3a9fba5d68e60de49a9baa6abfb4588f6a57e47c569e65194afce9ac40"
      define_method(:install) do
        bin.install "agento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/agento/releases/download/v0.11.2/agento_Linux_arm64.tar.gz"
      sha256 "2f98c2a4ceeb730794dfecf457848526d094750ac2a402b1b55ef158e6f8d725"
      define_method(:install) do
        bin.install "agento"
      end
    end
  end

  test do
    system "#{bin}/agento", "--version"
  end
end
