# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Echoy < Formula
  desc "Echoy - intelligent & smart AI assistance for your daily life"
  homepage "https://github.com/shaharia-lab/echoy"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.7/echoy_0.0.7_darwin_amd64.tar.gz"
      sha256 "2be7e67b7adc30e6f9a0cb9089f232a11ceaee6cfa3f0274d47e641c0f3b345a"

      def install
        bin.install "echoy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.7/echoy_0.0.7_darwin_arm64.tar.gz"
      sha256 "856d4d69f3942f6874e5c9320fc768a10dc0e937ae45c8423e55af8f12f2f45c"

      def install
        bin.install "echoy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.7/echoy_0.0.7_linux_amd64.tar.gz"
        sha256 "7e11e673f81339e68dcd9f5992e59feefd0e4d8e6c7690cafa3fd41e3ec3fdff"

        def install
          bin.install "echoy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.7/echoy_0.0.7_linux_arm64.tar.gz"
        sha256 "9e8e99496746290e611e7cb4c1a21288183139904262673b2c981df060796f1b"

        def install
          bin.install "echoy"
        end
      end
    end
  end

  test do
    system "#{bin}/echoy --version"
  end
end
