# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Echoy < Formula
  desc "Echoy - intelligent & smart AI assistance for your daily life"
  homepage "https://github.com/shaharia-lab/echoy"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.8/echoy_0.0.8_darwin_amd64.tar.gz"
      sha256 "2bf8fb3b0b514c60fa245725e0c5322ce805a18e4a563e69e2d36f5f93befdea"

      def install
        bin.install "echoy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.8/echoy_0.0.8_darwin_arm64.tar.gz"
      sha256 "06f8e85795dd1d14998accfd94d0493061d0f6f284ffae24190253ac153aa581"

      def install
        bin.install "echoy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.8/echoy_0.0.8_linux_amd64.tar.gz"
        sha256 "e07fffc94b1da6f94f447c9ea88e641f3ad8f7633a362ba56fd38651aebc14ef"

        def install
          bin.install "echoy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shaharia-lab/echoy/releases/download/v0.0.8/echoy_0.0.8_linux_arm64.tar.gz"
        sha256 "85e29407eaf9793a2d3e449800be9db778d9000bec51b784877b795a1cc920f2"

        def install
          bin.install "echoy"
        end
      end
    end
  end

  test do
    system "#{bin}/echoy --version"
  end
end
