# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleDriveCli < Formula
  desc "A comprehensive CLI tool for Unix-like filesystem operations on Google Drive"
  homepage "https://github.com/shaharia-lab/google-drive-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shaharia-lab/google-drive-cli/releases/download/v0.1.0/google-drive-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "b4bbd6d9c3e2a334e7d6c573c7893467e14a4cea5b76d485d0d38f43efcc8ede"

      def install
        bin.install "google-drive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shaharia-lab/google-drive-cli/releases/download/v0.1.0/google-drive-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "9cfd662e1a566eda76a1388271806f69b71736bac93e7ea2161ea41955ec47c9"

      def install
        bin.install "google-drive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/google-drive-cli/releases/download/v0.1.0/google-drive-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e75bc5359a094791f06929ea4eb3d26566a293f5430a0d7f9690f79f940ac471"
      def install
        bin.install "google-drive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaharia-lab/google-drive-cli/releases/download/v0.1.0/google-drive-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "f631ebf4ab63d8de4aaa811f0fd6c79daa429f54867abcac39b10d05502c2f46"
      def install
        bin.install "google-drive-cli"
      end
    end
  end

  test do
    system "#{bin}/google-drive-cli --help"
  end
end
