# typed: false
# frozen_string_literal: true

# Generated by the release workflow of https://github.com/shaharia-lab/jev-cli; do not edit.
class Jev < Formula
  desc "Unofficial CLI for TypeSafe AI's Jev model, for humans, scripts and AI agents"
  homepage "https://github.com/shaharia-lab/jev-cli"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.1/jev-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "dcc135bfd1403a8cd367a651a4e4a89618937f66af5d41eb24b353160cba2451"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.1/jev-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "f31c7df848c2d09a505fdd5008d49d8eab637209bf7f4e28882df8f6733dcaa8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.1/jev-0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "12bd15a6805f92ac25f3396e6d5419afd05778be9856f273039be479b52709ae"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.1/jev-0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "94fb6577e771d589991af6d140fdbb7009c090e69bcab92e644e8efbd36c0032"
    end
  end

  def install
    bin.install "jev"
    man1.install Dir["man/man1/*.1"]
    bash_completion.install "completions/jev.bash" => "jev"
    zsh_completion.install "completions/_jev"
    fish_completion.install "completions/jev.fish"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/jev version --field version").strip
  end
end
