# typed: false
# frozen_string_literal: true

# Generated by the release workflow of https://github.com/shaharia-lab/jev-cli; do not edit.
class JevAT020 < Formula
  desc "Unofficial CLI for TypeSafe AI's Jev model, for humans, scripts and AI agents"
  homepage "https://github.com/shaharia-lab/jev-cli"
  license any_of: ["MIT", "Apache-2.0"]

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.2.0/jev-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "9c1eb724e896ae01c857370bd1c0c11fea54af6c8e694ff266c27fb5b35dcc2e"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.2.0/jev-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "d122d700d28d8fe227eb19bd85856870fa41aa68ce2ff62b608a492d872f3bf5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.2.0/jev-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5fbda3609fb637f93fab9e8ca5edd5c1b7be6e4b3938f6f5372bfbb00b4ce41e"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.2.0/jev-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "877157b9481bcc2fa622688592fdaa8cf33b94e3ea08ef73c665f61d41880123"
    end
  end

  def install
    bin.install "jev"
    man1.install Dir["man/man1/*.1"]
    bash_completion.install "completions/jev.bash" => "jev"
    zsh_completion.install "completions/_jev"
    fish_completion.install "completions/jev.fish"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/jev version --field version").strip
  end
end
