# typed: false
# frozen_string_literal: true

# Generated by the release workflow of https://github.com/shaharia-lab/jev-cli; do not edit.
class JevAT010 < Formula
  desc "Unofficial CLI for TypeSafe AI's Jev model, for humans, scripts and AI agents"
  homepage "https://github.com/shaharia-lab/jev-cli"
  license any_of: ["MIT", "Apache-2.0"]

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.0/jev-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "32d2992da73728c4d74bee01cc804a395667008d836dddeec133f045b8507b7e"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.0/jev-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "46184a8df9f212e2078a177d2cc664a8f379dfa0682ddc126f5726809df331eb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.0/jev-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e6dbfa3a5a42265b1284c4856df59ad109a5976213626bac14c37ab3c235b51f"
    end
    on_intel do
      url "https://github.com/shaharia-lab/jev-cli/releases/download/v0.1.0/jev-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "cfe8f388d1cfb57f45864403688212787e496a050cf4ba7473e6c202542a2504"
    end
  end

  def install
    bin.install "jev"
    man1.install Dir["man/man1/*.1"]
    bash_completion.install "completions/jev.bash" => "jev"
    zsh_completion.install "completions/_jev"
    fish_completion.install "completions/jev.fish"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/jev version --field version").strip
  end
end
